#+title: Dorgygen: Source code documentation in org-mode
#+author: Stefano Ghirlanda
#+email: drghirlanda@gmail.com
#+options: toc:nil ':t
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage[scaled]{couriers}
#+latex_header: \usepackage[scaled]{berasans}
#+latex_header: \renewcommand\familydefault\sfdefault
#+latex_header: \hypersetup{colorlinks=true}
#+latex_header: \setlength{\parskip}{1.5ex}
#+latex_header: \setlength{\parindent}{0pt}

*WARNING: This is work in progress. It currently supports C and Python, but new languages can be added easily (see [[Adding a language]]).*

* Introduction

Dorgygen is an [[https://www.gnu/org/emacs][Emacs]] package to document source code in [[Https:///orgmode.org][Org]] documents with minimal setup. You may find it useful if you don't want/need full-blown literate programming and like source code without distracting markup. With dorgygen, source code is documented with short comments, which are then integrated with longer explanations in Org documents. Take this C file as an example:
#+begin_src C :exports code
  // the main function
  int                // exit value
  main( int argc,    // number of arguments
	char *argv[] // argument values
    );
#+end_src
We don't need special markup because dorgygen understands that, for example, "~// number of arguments~" is a comment about "~int argc~," which in turn is a parameter of the function ~main~ (courtesy of [[https://tree-sitter.github.io][tree-sitter]]). When it runs, dorgygen scans source files for comments and creates corresponding Org headings and subheadings. The example file above gives:
#+begin_src org :exports code
  ,* main.c

  ,** main

  - The main function.
  - In: ~int argc~. Number of arguments.
  - In: ~char *argv[]~. Argument values.
  - Out: ~int~. Exit value.
#+end_src
Once this documentation is generated, you can add more. For example:
#+begin_src org :exports code
  ,* main.c

  Here is documentation about the file.

  ,** main

  - The main function.
  - In: ~int argc~. Number of arguments.
  - In: ~char *argv[]~. Argument values.
  - Out: ~int~. Exit value.

  Here is documentation about the ~main~ function.
#+end_src
When run again, dorgygen updates documentation from source files and preserves your text. Note that user text must not contain list items (lines starting with ~-~), because dorgygen uses them to detect the beginning of auto-generated content.

* Installation

Dorgygen is available on [[https://melpa.org/#/dorgygen][MELPA]]. You can also install manually from [[https://github.com/drghirlanda/dorgygen][GitHub]].

* Using dorgygen
** Preparing source code

For a C project, one would typically add documentation comments to header files. The template for commenting a C function is
#+begin_src C :exports code
  // brief function documentation
  int // return type documentation
  function(
    int arg1, // argument documentation
    ...
    );
#+end_src
Any of the documentation comments can be omitted, and additional comments are ignored. You can format code to your liking, provided comments are placed appropriately, and you can use the ~/* ... */~ style.

A ~typedef~ is commented through a preceding comment:  
#+begin_src C :exports code
  // a new type
  typedef new_float_t float;
#+end_src
It will appear as a list item under the file-level heading. 

Comments introduced by ~//~ can span multiple lines, provided they are consecutive:
#+begin_src C :exports code
  // this function documentation
  // is longer than one line
  int // return type documentation
  function(
    int arg1, // this argument documentation
              // is also longer than one line
    ...
    );
#+end_src

** Python

For Python, load =dorgygen-python= in your init file:
#+begin_src elisp :exports code
(require 'dorgygen-python)
#+end_src
Documentation is extracted from *docstrings* (not =#= comments).
The template for a documented function is:
#+begin_src python :exports code
def process(items: list[str], max_count: int = 10) -> bool:
    """Process a list of items up to max_count."""
    pass
#+end_src
This generates:
#+begin_src org :exports code
,** ~process~
- Process a list of items up to max_count.
- param ~items~ : list[str]
- param ~max_count~ : int = 10
- returns : bool
#+end_src
Classes are documented with their own docstring, class-level variable
assignments that have a following string literal, and any methods that
have docstrings.  Methods without docstrings are omitted.

** Preparing org documents 

There is only one mandatory setting: one heading in the document should have the property ~DORG_REX~ set to a regular expression that matches the source files to be documented. For example, the following instructs dorgygen to document all C headers in the ~src~ directory:
#+begin_src org :exports code
  ,* Documentation
  :PROPERTIES:
  :DORG_REX: src/*\.h$
  :END:
#+end_src
Characters that are special in Emacs regular expressions must be escaped with a single backslash.

Dorgygen looks for the ~DORG_REX~ property starting from the heading at point and searching upward. Thus you can have multiple documentation sections in the same document, each with its own ~DORG_REX~ property.

The optional property ~DORG_LAN~ specifies a programming language. If it is not set, each file's extension is used to guess the language.   

** Generating documentation

After you have commented source files and prepared the Org document, you just run ~M-x dorgygen~. 

* Customization

Running ~M-x customize-group RET dorgygen~ gives access to some customization:

- ~dorgygen-attr-list~: The content of this variable is added before each list generated by dorgygen. For example, you can set it to ~#attr_latex: ...~ to customize LaTeX export. 

* Adding a language

To add support for a new language, call ~dorgygen-add-language~ in your init file. For example, here is how C is registered:
#+begin_src elisp :exports code
  (dorgygen-add-language 'c
    :extensions '("h" "c")
    :comments '("^//[ \t]*" "^/\\*[ \t]*" "[ \t]*\\*/$")
    :file-level '(("type_definition" . dorgygen--c-type_definition))
    :subheading '(("declaration" . dorgygen--c-declaration)))
#+end_src

The arguments are:
- The first argument is a language symbol understood by tree-sitter (e.g., ~c~, ~python~, ~go~).
- ~:extensions~ is a list of file extensions that identify files in this language.
- ~:comments~ is a list of regular expressions matched against comment text to strip comment markers.
- ~:file-level~ is an alist of =(TREESIT-TYPE . HANDLER)= pairs. Each handler is called with a tree-sitter node and should insert a list item (~- ...~) under the file heading.
- ~:subheading~ is an alist of =(TREESIT-TYPE . HANDLER)= pairs. Each handler is called with a tree-sitter node and an org level string (e.g., ~"***"~), and should insert an org subheading. It must return the heading text (for tracking), or nil to skip the node.

To find the tree-sitter node types for your language, open a source file in the corresponding ~<lang>-ts-mode~ and use ~M-x treesit-explore-mode~.

** Writing handlers

A *file-level handler* receives a tree-sitter node and should insert a list item at point. It can optionally return a value (which is ignored). Here is the built-in handler for C ~typedef~ declarations:
#+begin_src elisp :exports code
  (defun dorgygen--c-type_definition (tdef)
    "Document typedef declaration TDEF."
    (let ((def (string-replace ";" "" (treesit-node-text tdef)))
          (com (dorgygen--comment-about tdef)))
      (insert (format "- ~%s~.%s\n" def (if com (concat " " com) "")))))
#+end_src
Given ~// a new type~ followed by ~typedef my_float float;~, this inserts:
: - ~typedef my_float float~. A new type.

A *subheading handler* receives a tree-sitter node and an org level string (e.g., ~"***"~). It should insert a subheading with documentation and return the heading text for tracking purposes, or ~nil~ to skip the node. Here is the built-in handler for C function declarations (simplified for clarity):
#+begin_src elisp :exports code
  (defun my-c-declaration (ndec levl)
    "Document function declaration NDEC at org level LEVL."
    (let* ((fdec (car (dorgygen--find "function_declarator" ndec)))
           (fnam (treesit-node-text (treesit-node-child fdec 0 t)))
           (fhdn (dorgygen--heading fnam))  ; e.g., "~main~"
           (fret (treesit-node-child ndec 0 t))
           (fpar (treesit-node-child fdec 1 t))
           (exis (org-find-exact-headline-in-buffer fhdn)))
      (when (treesit-node-p fdec)
        ;; insert or update heading
        (if (not exis)
            (insert levl " " fhdn "\n\n")
          (goto-char exis)
          (forward-line)
          (dorgygen--delete-non-user-content))
        ;; insert documentation
        (let ((com (dorgygen--comment-about ndec)))
          (when com (insert "- " com "\n")))
        (dolist (par (treesit-filter-child fpar 'dorgygen--not-comment t))
          (let ((com (dorgygen--comment-about par t)))
            (insert (format "- In: ~%s~.%s\n"
                            (treesit-node-text par t)
                            (if com (concat " " com) "")))))
        (insert (format "- Out: ~%s~.\n\n" (treesit-node-text fret t)))
        fhdn)))  ; return heading for tracking
#+end_src

The key helper functions available to handlers are:
- ~dorgygen--comment-about~ :: Finds a comment adjacent to a node. Pass no extra argument to look before the node, or ~t~ to look after. Returns the cleaned-up, capitalized comment text, or ~nil~.
- ~dorgygen--find~ :: Finds all descendants of a given tree-sitter type within a node.
- ~dorgygen--heading~ :: Wraps a name in =~~= for use as an org heading.
- ~dorgygen--delete-non-user-content~ :: Deletes auto-generated content under the current heading while preserving user-written text.

* TODO Bugs

Please submit bugs and feature requests as [[https://github.com/drghirlanda/dorgygen/issues][issues on Github]].
